// 18-vue-basics/src/App.vue
<script lang="ts">
const todos = [
	{ id: 1, title: 'Make coffee', completed: true },
	{ id: 2, title: 'Drink coffee', completed: false },
	{ id: 3, title: 'Drink MOAR coffee', completed: false },
	{ id: 4, title: 'Drink ALL THE coffee', completed: false },
]

export default {
	data: function () {
		return {
			count: 0,
		}
	},
}

</script>

<template>
	<div class="container">
		<h1>Vue.js basics</h1>

		<section class="basics">
			<h2>MSG</h2>

			<p>You have clicked the button: {{ count }} times.</p>
			<button v-on:click="count++" class="btn btn-success btn-lg">Click meee! 😃</button>

			<hr />

			<div class="mb-3">
				<input type="text" class="form-control" placeholder="Enter your name" />
			</div>

			<p>Hello, USERNAME!</p>
		</section>

		<hr />

		<section class="todos">
			<h2>Todos</h2>
			<ul>
				<li>I am a procastrinated todo 😰</li>
				<li class="completed">I am a completed todo 😁</li>
			</ul>
		</section>

		<hr />

		<section class="salary">
			<p>Salary per hour: <span>SALARY &euro;</span></p>

			<img src="/src/assets/images/salary.png" class="img-fluid img-salary" />

			<div class="buttons">
				<div class="mb-1">
					<button class="btn btn-primary btn-lg">Raise 1 &euro; 🤑</button>

					<button class="btn btn-warning btn-lg">Decrease 1 &euro; 😢</button>
				</div>
				<div>
					<button class="btn btn-success btn-lg">Increase 5 &euro; 🤑🤑🤑</button>

					<button class="btn btn-danger btn-lg">Decrease 5 &euro; 😢😢😢</button>
				</div>
			</div>
		</section>

		<hr />

		<section class="box">
			<div class="mb-3">
				<button class="btn btn-primary btn-lg">🏃🏻</button>
			</div>

			<div class="grey-box">
				<div class="coords">42, 1337</div>
			</div>

			<p class="d-none">No 📦 for you!</p>
		</section>
	</div>
</template>

// 01-react-basics/src/App.tsx
import { useState } from 'react'
import './App.css'

type Post = {
	id: number
	title: string
	likes: number
}

const App = () => {
	const [msg, setMsg] = useState('Hi mom')
	const [clicks, setClicks] = useState(0)
	const [posts, setPosts] = useState<Post[]>([
		{ id: 1, title: 'React Rocks!', likes: 420 },
		{ id: 2, title: 'TypeScript is lit!', likes: 1337 },
		{ id: 3, title: 'CSS?...', likes: 69 },
	])
	const [salary, setSalary] = useState(10)

	const handleButtonClick = () => {
		setMsg('Bye mom')
		setClicks(clicks + 1)
	}

	const handleSalaryFlucuation = (amount: number) => {
		const newSalary = salary + amount

		setSalary(newSalary)

		if (newSalary < 5) setSalary(5)
	}

	return (
		<div className="App">
			<h1>React Basics</h1>
			<h2>{msg}</h2>
			<p>You have clicked the button {clicks} times.</p>
			<button onClick={handleButtonClick} className="btn btn-success btn-lg">Click me!</button>
			<button onClick={() => setMsg('Hi dad!')} className="btn btn-warning btn-lg">Hi dad!</button>

			<hr />

			<p>Salary per hour: {salary} &euro;</p>

			{salary < 10 && <div>GET A NEW JOB BRO!</div>}

			<div className="buttons">
				<div className="mb-1">
					<button onClick={() => handleSalaryFlucuation(-1)} className="btn btn-warning btn-lg">Decrease 1 &euro; 😢</button>
					<button onClick={() => handleSalaryFlucuation(1)} className="btn btn-primary btn-lg">Raise 1 &euro; 🤑</button>
				</div>

				<div className="mb-1">
					<button onClick={() => handleSalaryFlucuation(-5)} className="btn btn-danger btn-lg">Decrease 5 &euro; 😢😢😢</button>
					<button onClick={() => handleSalaryFlucuation(5)} className="btn btn-success btn-lg">Raise 5 &euro; 🤑🤑🤑</button>
				</div>
			</div>

			<h2>Posts</h2>

			<ul>
				{posts.map((post, index) => <li key={index}>{post.title} ({post.likes} likes)</li>)}
			</ul>
		</div>
	)
}

export default App
